from turtle import *

def fon():
    speed(10)
    penup()
    goto(-250,-150)
    begin_fill()
    color('green')
    pendown()
    forward(500)
    right(90)
    forward(200)
    right(90)
    forward(500)
    right(90)
    forward(200)
    end_fill()
    begin_fill()
    color('sky blue')
    forward(400)
    right(90)
    forward(500)
    right(90)
    forward(400)
    right(90)
    forward(500)
    right(90)
    end_fill()

def sun():
    speed(1000)
    penup()
    color('yellow')
    speed(10)
    goto(200,150)
    pendown()
    begin_fill()
    for i in range(25):
        right(70)
        forward(50)
        right(70)
        forward(50)
        right(70)
        forward(50)
        left(15)
    end_fill()

def clouds():
    penup()
    left(90)
    goto(40, 160)
    color('white')
    pendown()
    begin_fill()
    right(10)
    circle(35)
    right(90)
    forward(5)
    circle(40)
    right(90)
    forward(5)
    circle(34)
    end_fill()

def house():
    right(65)
    penup()
    goto(-200, -190)
    color('gray')
    pendown()
    begin_fill()
    right(90)
    forward(200)
    left(90)
    forward(350)
    left(90)
    forward(200)
    left(90)
    forward(350)
    end_fill()
    penup()
    goto(-100,-190)
    pendown()
    begin_fill()
    color('black')
    left(90)
    forward(50)
    left(90)
    forward(70)
    left(90)
    forward(50)
    left(90)
    forward(70)
    left(90)
    end_fill()
    penup()
    goto(-190,50)
    pendown()
    color('Yellow')
    begin_fill()
    for i in range (3):
        for i in range (4):
            forward(50)
            left(90)
        penup()
        forward(60)
        pendown()
    end_fill()
    penup()
    goto(-190, -50)
    pendown()
    begin_fill()
    for i in range (3):
        for i in range (4):
            forward(50)
            left(90)
        penup()
        forward(60)
        pendown()
    end_fill()
 
def fence_link():
    penup()
    goto(-250,-190)
    pendown()
    pensize(2)
    color("black","orange")
    for i in range(6):
        begin_fill()
        left(90)
        forward(50)
        right(30)
        forward(22)
        right(120)
        forward(22)
        right(30)
        forward(50)
        right(90)
        forward(22)
        left(180)
        end_fill()
        forward(22)
        end_fill()

def tree(x,y,x1,y1):
    penup()
    color('brown')
    goto(x,y)
    pendown()
    begin_fill()
    forward(30)
    left(90)
    forward(150)
    left(90)
    forward(30)
    left(90)
    forward(150)
    end_fill()
    penup()
    goto(x1, y1)
    begin_fill()
    color('green')
    pendown()
    circle(50)
    end_fill()
    penup()

fon()
sun()
clouds()
house()
fence_link()



